name: Website
on:
  push:
    branches:
      - master 
  pull_request:

jobs:
  # TODO: Implement tests for Rust samples included in documentation.
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     - name: Install Just
  #       run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin
  #     - name: Run Website Doc Tests
  #       run: just website-doc-tests

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_ONLY: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: ./public

